### ISSUE TITLE
[Feature Request] Create uninstall.sh to uninstall this setup

### ISSUE THREAD

**Issue by jahway603** [theGeeBee/NextCloudOnFreeBSD#12]
Feature Request to create uninstall.sh, which would enable the user to uninstall this setup.

**Comment by theGeeBee** [comment]
That can definitely be done. 

Will look in to making sure it works with all possible options. 

What's your particular need for this?

**Comment by jahway603** [comment]
@theGeeBee my particular need for this is to test this setup on FreeBSD 14.x, as after running this it does not work & trying to determine why. I will file a separate new issue for that.

**Comment by theGeeBee** [comment]
I have updated the script to disable HSTS if SSL is disabled.

I have also set up automatic public SSL certificates. Please try again and let me know, I am still working on an uninstall that works with all available options

**Comment by jahway603** [comment]
Should this issue remain open until an uninstall script is available?
